/**
 * @description       : 
 * @author            : sgrosset@main.lwc.dreamhouse.sfdc.eoex.com
 * @group             : 
 * @last modified on  : 06-06-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class HelloWorld 
{
    /**
    * @description 
    * @author sgrosset@main.lwc.dreamhouse.sfdc.eoex.com | 06-06-2025 
    **/
    public HelloWorld() 
    {
        System.debug('Hello World !');
        System.debug('From Sosthene Grosset-Janin');
    }
}